### ISSUE TITLE
oracle dump file outside container

### ISSUE THREAD

**Issue by huy91-hub** [mpern/oracle-docker#1]
I use docker in centos7, you did not mention that platform. I have a dump file outside container. Can I import dumped file from the path outside container, certain in host machine. Thank you in advance.

**Comment by mpern** [comment]
That's how it works already.
The `dump` folder is outside the container, on the host, and mounted into the container at `/opt/oracle/dump`

You might want to lookup 'bind mounts' 😉

**Comment by huy91-hub** [comment]
> That's how it works already. The `dump` folder is outside the container, on the host, and mounted into the container at `/opt/oracle/dump`
> 
> You might want to lookup 'bind mounts' 😉

Ok thank @mpern. I found it.
